# -*- coding: utf-8 -*-
"""Creditcard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftL-339WHL054Nwbp8wA3BzOSHjoEs7u
"""

# ============================================================
#   Credit Card Fraud Detection Patterns
#   Domain  : Finance
#   Tasks   : Clean + Anomaly Detection + Scatter + Histogram
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import classification_report
from scipy import stats

# ============================================================
# STEP 1 — LOAD & CLEAN DATA
# ============================================================

df = pd.read_csv('/content/drive/MyDrive/Sample Datasets/creditcard.csv')

print("=" * 50)
print("STEP 1 — LOAD & CLEAN DATA")
print("=" * 50)
print("Shape:", df.shape)
print("\nClass Distribution:\n", df['Class'].value_counts())
print("\nFraud %:", round(df['Class'].mean() * 100, 4), "%")
print("\nMissing Values:", df.isnull().sum().sum())

before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"Duplicates Removed: {before - after}")
print("Clean Dataset Shape:", df.shape)

# ============================================================
# STEP 2 — IDENTIFY FRAUD PATTERNS
# ============================================================

print("\n" + "=" * 50)
print("STEP 2 — IDENTIFY FRAUD PATTERNS")
print("=" * 50)

fraud = df[df['Class'] == 1]
legit = df[df['Class'] == 0]

print("=== Amount Patterns ===")
print("Avg Amount - Legit :", round(legit['Amount'].mean(), 2))
print("Avg Amount - Fraud :", round(fraud['Amount'].mean(), 2))
print("Max Amount - Fraud :", round(fraud['Amount'].max(), 2))
print("Min Amount - Fraud :", round(fraud['Amount'].min(), 2))

print("\n=== Time Patterns ===")
print("Fraud peak time (seconds):", round(fraud['Time'].mean(), 2))
print("Legit peak time (seconds):", round(legit['Time'].mean(), 2))

print("\n=== Top Features Correlated with Fraud ===")
corr = df.corr()['Class'].drop('Class').abs().sort_values(ascending=False)
print(corr.head(10))

# ============================================================
# STEP 3 — ANOMALY DETECTION
# ============================================================

print("\n" + "=" * 50)
print("STEP 3 — ANOMALY DETECTION")
print("=" * 50)

scaler = StandardScaler()
df['Amount_scaled'] = scaler.fit_transform(df[['Amount']])
df['Time_scaled']   = scaler.fit_transform(df[['Time']])

X = df.drop(['Class', 'Amount', 'Time'], axis=1)
y = df['Class']

X_sample = X.sample(5000, random_state=42)
y_sample = y.loc[X_sample.index]

# Isolation Forest
iso = IsolationForest(contamination=0.002, random_state=42)
iso_preds = iso.fit_predict(X_sample)
iso_preds = (iso_preds == -1).astype(int)
print("=== Isolation Forest ===")
print(classification_report(y_sample, iso_preds))

# Local Outlier Factor
lof = LocalOutlierFactor(n_neighbors=20, contamination=0.002)
lof_preds = lof.fit_predict(X_sample)
lof_preds = (lof_preds == -1).astype(int)
print("=== Local Outlier Factor ===")
print(classification_report(y_sample, lof_preds))

# Z-Score
z_scores = np.abs(stats.zscore(df['Amount_scaled']))
df['amount_outlier'] = (z_scores > 3).astype(int)
print("Z-Score Flagged Transactions:", df['amount_outlier'].sum())

# ============================================================
# STEP 4 — HISTOGRAM PLOTS
# ============================================================

print("\n" + "=" * 50)
print("STEP 4 — HISTOGRAM PLOTS")
print("=" * 50)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].hist(legit['Amount'], bins=60, alpha=0.6,
             label='Legit', color='steelblue')
axes[0].hist(fraud['Amount'], bins=60, alpha=0.7,
             label='Fraud', color='crimson')
axes[0].set_title("Transaction Amount Distribution")
axes[0].set_xlabel("Amount ($)")
axes[0].set_ylabel("Count")
axes[0].legend()

axes[1].hist(legit['Time'], bins=60, alpha=0.6,
             label='Legit', color='steelblue')
axes[1].hist(fraud['Time'], bins=60, alpha=0.7,
             label='Fraud', color='crimson')
axes[1].set_title("Transaction Time Distribution")
axes[1].set_xlabel("Time (seconds)")
axes[1].set_ylabel("Count")
axes[1].legend()

plt.suptitle("Histogram Analysis — Fraud vs Legit", fontsize=14)
plt.tight_layout()
plt.savefig('histogram.png')
plt.show()
print("Histogram saved as histogram.png")

# ============================================================
# STEP 5 — SCATTER PLOTS
# ============================================================

print("\n" + "=" * 50)
print("STEP 5 — SCATTER PLOTS")
print("=" * 50)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].scatter(legit['V1'], legit['V2'],
                alpha=0.1, s=5, label='Legit', color='steelblue')
axes[0].scatter(fraud['V1'], fraud['V2'],
                alpha=0.6, s=15, label='Fraud', color='crimson')
axes[0].set_title("Scatter: V1 vs V2")
axes[0].set_xlabel("V1")
axes[0].set_ylabel("V2")
axes[0].legend()

axes[1].scatter(legit['Time'], legit['Amount'],
                alpha=0.05, s=5, label='Legit', color='steelblue')
axes[1].scatter(fraud['Time'], fraud['Amount'],
                alpha=0.6, s=15, label='Fraud', color='crimson')
axes[1].set_title("Scatter: Time vs Amount")
axes[1].set_xlabel("Time (seconds)")
axes[1].set_ylabel("Amount ($)")
axes[1].legend()

plt.suptitle("Scatter Analysis — Fraud vs Legit", fontsize=14)
plt.tight_layout()
plt.savefig('scatter.png')
plt.show()
print("Scatter plot saved as scatter.png")

# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 50)
print("FINAL SUMMARY")
print("=" * 50)
print("Total Transactions     :", df.shape[0])
print("Fraud Transactions     :", fraud.shape[0])
print("Legit Transactions     :", legit.shape[0])
print("Missing Values         : 0")
print("Duplicates Removed     : 0")
print("Z-Score Flagged        :", df['amount_outlier'].sum())
print("Top Fraud Feature      :", corr.index[0])
print("Histogram Plot Saved   : histogram.png")
print("Scatter Plot Saved     : scatter.png")
print("=" * 50)
print("Project Completed Successfully!")